### ISSUE TITLE
Function IsSoundReady does not exist?

### ISSUE THREAD

**Issue by ruttensa** [shiryel/rayex#14]
When trying to compile on macOS 14.7.1 on a MacBook Air M2, I get:
```
$ iex -S mix
Erlang/OTP 27 [erts-15.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace]

==> rayex
Bundlex: Building natives: rayex
/Users/ludo/Documents/prog/elixir/raylib01/deps/rayex/c_src/rayex/rayex.c:662:14: error: call to undeclared function 'IsSoundReady'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  662 |   bool res = IsSoundReady(sound);
```

It looks like the function `IsSoundReady` does not exist in raylib when I check the cheatsheet. Any idea ? TIA

**Comment by lkuty** [comment]
I used the wrong github account to post the issue but I will follow with this account. So don't be suprised if you see me replying instead of @ruttensa.

**Comment by teatwig** [comment]
The function was renamed in raylib 5.5 and rayex hasn't been updates since.
